### PR TITLE
Download ojdbc6 and xdb6 Within Dockerfiles

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
Edited docker files to agree to license agreement and download ojdbc6 which meets oracle license agreement. Removed ojdbc7.jar binaries.

Solves #1

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
Don't merge. I'm having inconsistent results on build. I will update when I have a consistent build.

**Comment by ericallen** [comment]
Thanks, I completely forgot about that.  I am wonder if they would be better suited to be in the tomcat run instead of a separate run.  Mostly to keep the number of images down.  In my thought process it is part of the tomcat setup so it should be included.

**Comment by ChristopherDavenport** [comment]
Umm So I hadn't completed the get request issue as it is pulling up an error http state for some reason so what this image currently pulls into xdb6.jar and ojdbc6.jar is a text html document, atleast in some of my tests. Is the image build from this able to connect to the db for you?

**Comment by ericallen** [comment]
Yeah I think I was a little approve happy.  I don't think this is going to work.  You are using the same download style as the jdk.  This doesn't work because the ojdbc6.jar and xdb6.jar are behind auth credentials and not just cookie.  I'm looking at how to download them as part of the dockerfile build.

**Pull request merged**
